baseURL: https://dshah-wlw.github.io/
languageCode: en-us
title: dshah's site
paginate: 5
theme: PaperModX

params:
# customisations
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  enableRobotsTXT: true
  pygmentsUseClasses: true
  description: my site
  author:
    - dshah

# set up home info details
  homeInfoParams:
      Title: Hi there ðŸ‘‹
      Content: My name is dshah
  socialIcons:
    - name: github-simple
      url: "https://github.com/dshah-wlw"
    - name: linkedin-simple
      url: "https://linkedin.com/"
    - name: email
      url: "test@example.com"
# production so more features are enabled
  env: production

# Navigation

menu:
  main:
    - identifier: home
      name: home
      url: "https://dshah-wlw.github.io"
      weight: 10
    - identifier: posts
      name: posts
      url: "/posts/"
      weight: 20 